### ISSUE TITLE
类型转换异常啊，大佬。

### ISSUE THREAD

**Issue by longxuewei** [wuhenzhizao/android-titlebar#24]
```
java.lang.ClassCastException: com.android.layoutlib.bridge.android.BridgeContext cannot be cast to 

android.content.ContextWrapper   at 

com.wuhenzhizao.titlebar.widget.CommonTitleBar.getWindow(CommonTitleBar.java:645)   at 

com.wuhenzhizao.titlebar.widget.CommonTitleBar.setUpImmersionTitleBar(CommonTitleBar.java:627) 

  at com.wuhenzhizao.titlebar.widget.CommonTitleBar.onAttachedToWindow(CommonTitleBar.java:623) 

  at android.view.View.dispatchAttachedToWindow(View.java:17445)   at 

android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3326)   at 

android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3333)   at 

android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3333)   at 

android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3333)   at 

android.view.AttachInfo_Accessor.setAttachInfo(AttachInfo_Accessor.java:42) Copy stack to clipboard   Tip: Try to refresh the layout.
```
在布局的时候出现了这个是咋回事？

**Comment by wuhenzhizao** [comment]
传入的上下文不是ContextWrapper，这个BridgeContext是自己封装的上下文类型吗

**Comment by longxuewei** [comment]
并不是啊，我在xml 文件里面布局的时候， 就提示无法预览。有问题。

**Comment by longxuewei** [comment]
我再换一个工程试试。

**Comment by longxuewei** [comment]
> 传入的上下文不是ContextWrapper，这个BridgeContext是自己封装的上下文类型吗
这是我的布局
```
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">


    <com.wuhenzhizao.titlebar.widget.CommonTitleBar
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:centerText="标题栏">

    </com.wuhenzhizao.titlebar.widget.CommonTitleBar>


    <TextView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:text="hahaha" />

</LinearLayout>
```

然后右边显示不能预览，有个红色叹号，然后下面爆出的错误是：

```
Turn off custom view rendering sandboxExec access not allowed during rendering (getprop)   at 
java.lang.ProcessBuilder.start(ProcessBuilder.java:1018)   at java.lang.Runtime.exec(Runtime.java:620)   at 
java.lang.Runtime.exec(Runtime.java:450)   at java.lang.Runtime.exec(Runtime.java:347)   at 
com.wuhenzhizao.titlebar.statusbar.OSUtils.getProp   ... (OSUtils.java:101)   at 
com.wuhenzhizao.titlebar.statusbar.OSUtils.check(OSUtils.java:75)   at 
com.wuhenzhizao.titlebar.statusbar.OSUtils.isMiui(OSUtils.java:33)   at 
com.wuhenzhizao.titlebar.statusbar.StatusBarUtils.supportTransparentStatusBar(StatusBarUtils.java:20) 
  at com.wuhenzhizao.titlebar.widget.CommonTitleBar.initGlobalViews(CommonTitleBar.java:264)   at 
com.wuhenzhizao.titlebar.widget.CommonTitleBar.<init>(CommonTitleBar.java:185)   at 
java.lang.reflect.Constructor.newInstance(Constructor.java:423)   at 
android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)   at 
android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:863)   at 
android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:72)   at 
android.view.LayoutInflater.rInflate(LayoutInflater.java:837)   at 
android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)   at 
android.view.LayoutInflater.inflate(LayoutInflater.java:515)   at 
android.view.LayoutInflater.inflate(LayoutInflater.java:394) Copy stack to clipboard   Tip: Try to refresh the 

layout.

```

看看是啥问题 ：）

**Comment by wuhenzhizao** [comment]
这个就是不支持预览，引入了非视图的java代码，和你上面提的那个错误没有关系

**Comment by Derek-Zh** [comment]
我也是，不能预览太麻烦了

**Comment by wuhenzhizao** [comment]
最近更新一版
