### ISSUE TITLE
 Binary XML file line #0

### ISSUE THREAD

**Issue by lichao3140** [wuhenzhizao/android-titlebar#7]
android.view.InflateException: Binary XML file line #0: Error inflating class <unknown>

**Comment by lichao3140** [comment]
android.view.InflateException: Binary XML file line #0: Error inflating class com.wuhenzhizao.titlebar.widget.CommonTitleBar
                                                                             at android.view.LayoutInflater.createView(LayoutInflater.java:623)
                                                                             at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:699)
                                                                             at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:400)
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
                                                                             at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
                                                                             at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
                                                                             at com.a1byone.bloodpressure.ui.activity.RegisterActivity.onCreate(RegisterActivity.java:13)
                                                                             at android.app.Activity.performCreate(Activity.java:5356)
                                                                             at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2163)
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2258)
                                                                             at android.app.ActivityThread.access$800(ActivityThread.java:147)
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1211)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                             at android.os.Looper.loop(Looper.java:136)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5135)
                                                                             at java.lang.reflect.Method.invokeNative(Native Method)
                                                                             at java.lang.reflect.Method.invoke(Method.java:515)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:798)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:614)
                                                                             at dalvik.system.NativeStart.main(Native Method)
                                                                          Caused by: java.lang.reflect.InvocationTargetException
                                                                             at java.lang.reflect.Constructor.constructNative(Native Method)
                                                                             at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
                                                                             at android.view.LayoutInflater.createView(LayoutInflater.java:597)
                                                                             at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:699) 
                                                                             at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:495) 
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:400) 
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
                                                                             at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287) 
                                                                             at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
                                                                             at com.a1byone.bloodpressure.ui.activity.RegisterActivity.onCreate(RegisterActivity.java:13) 
                                                                             at android.app.Activity.performCreate(Activity.java:5356) 
                                                                             at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2163) 
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2258) 
                                                                             at android.app.ActivityThread.access$800(ActivityThread.java:147) 
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1211) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                             at android.os.Looper.loop(Looper.java:136) 
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5135) 
                                                                             at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                             at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:798) 
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:614) 
                                                                             at dalvik.system.NativeStart.main(Native Method) 
                                                                          Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x0
                                                                             at android.content.res.Resources.getValue(Resources.java:1133)
                                                                             at android.content.res.MiuiResources.getValue(MiuiResources.java:145)
                                                                             at android.content.res.Resources.loadXmlResourceParser(Resources.java:2383)
                                                                             at android.content.res.Resources.getLayout(Resources.java:949)
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
                                                                             at com.wuhenzhizao.titlebar.widget.CommonTitleBar.initMainLeftViews(CommonTitleBar.java:369)
                                                                             at com.wuhenzhizao.titlebar.widget.CommonTitleBar.initMainViews(CommonTitleBar.java:313)
                                                                             at com.wuhenzhizao.titlebar.widget.CommonTitleBar.<init>(CommonTitleBar.java:175)

**Comment by wuhenzhizao** [comment]
是否设置了leftType= customView，却没有配置对应的leftCustomView属性

**Comment by wuhenzhizao** [comment]
具体用法可以参考README，demo

**Comment by lichao3140** [comment]
<com.wuhenzhizao.titlebar.widget.CommonTitleBar
        xmlns:titlebar="http://schemas.android.com/apk/res-auto"
        android:id="@+id/login_title_bar"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        titlebar:titleBarColor="@color/md_cyan_A800"
        titlebar:centerText="@string/login"
        titlebar:centerType="textView"
        titlebar:centerTextColor="@color/accent_white"
        titlebar:rightText="@string/go_to_register"
        titlebar:rightType="textView"
        titlebar:rightTextColor="@color/accent_green"/>

**Comment by lichao3140** [comment]
我前两天运行也是可以的，后来我我改了stylesl里面的属性，就出问题了， 我查网上是不是要把另外两个构造方法都加上
public CommonTitleBar(Context context, AttributeSet attrs) {
        super(context, attrs);
        loadAttributes(context, attrs);
        initGlobalViews(context);
        initMainViews(context);
    }

**Comment by wuhenzhizao** [comment]
你报的这个错误就是因为配置了titlebar:leftType="customView"，却没有配置leftCustomView
